# Generated by Django 4.2.2 on 2023-07-13 20:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
