# Generated by Django 4.2.2 on 2023-07-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactenquiry_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactenquiry',
            name='name',
        ),
    ]
