# Generated by Django 4.2.2 on 2023-07-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactenquiry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
