# Generated by Django 4.2.2 on 2023-07-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactenquiry_email_alter_contactenquiry_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
