# Generated by Django 4.2.2 on 2023-07-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contactenquiry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
