# Generated by Django 4.2.2 on 2023-07-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_contactenquiry_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
